### ISSUE TITLE
Feature Request: Support expo server functions in template

### ISSUE THREAD

**Issue by johannbuscail** [roninoss/create-expo-stack#431]
It would be amazing to have Expo Server Functions support.

**Comment by dannyhw** [comment]
Whilst i agree this could be cool, but since it's still experimental adding it to the base template doesn't feel right. I also think adding it from the expo guide is only a few steps right? 

It's also unclear to me if it should be under the scope of CES, like are we then saying that apps should be full stack in expo router. Feels like it's too early to say that.

**Comment by danstepanov** [comment]
expo server functions are still experimental, I agree with Danny. Closing this.
